name: CI

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps (Node)
        if: ${{ hashFiles('**/package.json') != '' }}
        run: |
          npm ci

      - name: Install deps (Python)
        if: ${{ hashFiles('**/pyproject.toml') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Lint/Format
        run: |
          if [ -f package.json ]; then npm run -s lint && npm run -s format:check; fi
          if [ -f pyproject.toml ]; then ruff . && black --check .; fi

      - name: Tests
        run: |
          if [ -f package.json ]; then npm test -- --coverage; fi
          if [ -f pyproject.toml ]; then pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=term; fi

      - name: Security (Semgrep)
        run: |
          pip install semgrep || true
          semgrep scan --config auto --error .

      - name: Secrets (Gitleaks)
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          ./gitleaks detect --no-banner --redact --exit-code 1

      - name: Domain Diff (changed tests)
        run: |
          node scripts/diff_advanced.cjs origin/main || node scripts/diff_advanced.cjs

      - name: Diff Test Pattern
        run: |
          node scripts/diff_test.cjs origin/main || node scripts/diff_test.cjs

      - name: Affected Domains
        run: |
          node scripts/affected_domains.cjs

      - name: Generate Domain Smoke Tests
        run: |
          node scripts/generate_domain_smoke_tests.cjs

      - name: Interface Diff
        run: |
          node scripts/interface_diff.cjs

      - name: Contract Check
        run: |
          node scripts/contract_check.cjs

      - name: Smoke Analyze
        run: |
          node scripts/smoke_analyze.cjs

      - name: Smoke Gate
        run: |
          pwsh -NoProfile -ExecutionPolicy Bypass -File scripts/check_smoke.ps1

      - name: Aggregate Reports
        run: |
          pwsh -NoProfile -ExecutionPolicy Bypass -File scripts/run_reports.ps1
