
name: security
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
  security-events: write
jobs:
  sast_and_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
